name: laba 3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v1
      - name: install valgrind and cpplint
      
        run: |
          sudo apt install valgrind
          sudo pip install cpplint
      - name: compiling and test
        
        run: |
            make -C laba 3/
